spring.application.name=saas-task-manager-api
spring.datasource.url=jdbc:postgresql://localhost:5432/saas-db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update